using Microsoft.Extensions.FileProviders;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PUCCI.Models
{
    public class Image
    {
        // ID and Image ID are different
        // ID is Primary Key in DB and ImageID is generated by Docker
        public int? ID { get; set; }
        public string? ImageID { get; set; }
        [Required]
        public string? Name { get; set; }
        public string? Tag { get; set; }
        public string? Created { get; set; }

        // Path to Dockerfile in webroot
        public string? DockerfilePath { get; set; }
    }
}
