using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace PUCCI.Models
{
    public class Image
    {
        public void Create()
        {
            try
			{
				var shell = "";
				var command = $"docker build -t {Name} -f {DockerfilePath} wwwroot/Dockerfiles/";

				// Check environment
				// Need cmd for development and bash for when we dockerize
				if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
				{
					shell = "cmd.exe";
					command = "/C " + command;
				}
				else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
				{
					shell = "/bin/bash";
					command = "-c " + command;
				}

				using (var process = new Process())
				{
					process.StartInfo = new ProcessStartInfo
					{
						WindowStyle = ProcessWindowStyle.Maximized,
						FileName = shell,
						Arguments = command,
						UseShellExecute = true
					};
					process.Start();
				}
			}
			catch
            {
                throw;
            }
        }

        // ID and Image ID are different
        // ID is Primary Key in DB and ImageID is generated by Docker
        public int? ID { get; set; }
        public string? ImageID { get; set; }
        [Required]
        public string? Name { get; set; }
        public string? Tag { get; set; }
        public string? Created { get; set; }

        // Path to Dockerfile in webroot
        public string? DockerfilePath { get; set; }
    }
}
